models.py
import re
from datetime import datetime
from app import db
from flask_security import UserMixin, RoleMixin

def slugify(s):
    pattern = r'[^\w+]'
    return re.sub(pattern, '-', s)
    
posts_tags = db.Table('posts_tags',
                      db.Column('post_id', db.Integer,
                      db.ForeignKey('post.id')),
                      db.Column('tag_id', db.Integer,
                      db.ForeignKey('tag.id'))              
)


roles_users = db.Table('roles_users',
                      db.Column('user_id', db.Integer,
                      db.ForeignKey('user.id')),
                      db.Column('role_id', db.Integer,
                      db.ForeignKey('role.id'))              
)


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(140))
    slug = db.Column(db.String(140), unique=True)
    body = db.Column(db.Text)
    created = db.Column(db.DateTime, default=datetime.now())
    tags =  db.relationship('Tag', secondary=posts_tags, backref=db.backref('posts'), lazy='dynamic')
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.generate_slug()
        
    def generate_slug(self):
        if self.title:
            self.slug = slugify(self.title)
            
        else:
            self.slug = str(int(time()))
            
    def __repr__(self):
        return f'<Post id: {self. id}, title: {self.title}'
    
    
class Tag(db.Model):
    id  = db.Column(db.Integer, primary_key=True)
    title  = db.Column(db.String(140))
    slug  = db.Column(db.String(140), unique=True)
    
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.slug = self.generate_slug()
    
    
    def generate_slug(self):
        if self.title:
            self.slug = slugify(self.title)
            
        else:
            self.slug = str(int(time()))
 
    
    def __repr__(self):
        return f'<Tag id: {self.id}, title: {self.title}>'
        
 
 
class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(255))
    active = db.Column(db.Boolean)
    roles = db.relationship('Role', secondary=roles_users, 
    backref=db.backref('users'), lazy='dynamic')
    
    
class Role(db.Model, RoleMixin):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), unique=True)

posts/forms.py
from wtforms import Form, StringField, TextAreaField

class PostForm(Form):
    title = StringField("Title")
    body = TextAreaField("Body")
    

app.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate  import Migrate, MigrateCommand
from flask_script import Manager
from config import Config
from flask_admin import Admin
from flask_admin import AdminIndexView
from flask_admin.contrib.sqla import ModelView
from flask_security import SQLAlchemyUserDatastore
from flask_security import Security
from flask_security import current_user
from flask import redirect, url_for, request

app = Flask(__name__)
app.config.from_object(Config)

db = SQLAlchemy(app)

from models import*
migrate = Migrate(app, db)
manager = Manager(app)

manager.add_command('db', MigrateCommand)


class AdminMixin:
    def is_accessible(self):
        return current_user.has_role('admin')
        
    def inaccessible_callback(self, name, **kwargs):
        return redirect(url_for('security.login', next=request.url))


class AdminView(ModelView):
    pass


class HomeAdminView(AdminIndexView):
    pass
    
    
class BaseModelView(ModelView):
    def on_model_change(self, form, model, is_created):
        if is_created:
            model.generate_slug()
            
        return super().on_model_change(form, model, is_created)


class PostAdminView(AdminMixin, BaseModelView):
    form_columns = ['title', 'body', 'tags']
    

class TagAdminView(AdminMixin, BaseModelView):
    pass


admin = Admin(app, 'Aplicação ICO', url='/', index_view=HomeAdminView(name='Painel de Controle'))
admin.add_view(PostAdminView(Post, db.session))
admin.add_view(TagAdminView(Tag, db.session))
admin.add_view(AdminView(Role, db.session))
admin.add_view(AdminView(User, db.session))

# Flask-Security

user_datastore = SQLAlchemyUserDatastore(db, User, Role)
security = Security(app, user_datastore)

main.py
from app import app
import views
from app import db
from posts.blueprint import posts

app.register_blueprint(posts, url_prefix="/blog")




if __name__=='__main__':
    app.run()

posts/blueprint.py
from flask import Blueprint
from flask import render_template
from models import Post
from flask_security import login_required
from flask import request
from .forms import PostForm
from flask import redirect
from flask import url_for
from models import Post
from app import app, db
app.app_context().push()



posts = Blueprint('posts', __name__, template_folder='templates')





@posts.route('/')
@login_required
def posts_list():
    q = request.args.get('q')
    if q:
        posts = Post.query.filter(Post.title.contains(q) | 
        Post.body.contains(q)).all()
    else:
        posts = Post.query.order_by(Post.created.desc())
    return render_template('posts/posts.html', posts=posts)
    

@posts.route('/<slug>')
@login_required
def post_detail(slug):
    post = Post.query.filter(Post.slug==slug).first()
    return render_template('posts/post_detail.html',  post=post)


@posts.route('/create', methods=['POST', 'GET'])
@login_required
def post_create():
    form = PostForm()
    
    if request.form.get('title'):
        title = request.form.get('title')
        body = request.form.get('body')
        try:
            post = Post(title=title, body=body)
            db.session.add(post)
            db.session.commit()
            return redirect(url_for('posts.post_detail', slug=post.slug))
            
        except:
            print('Very long Traceback')
            return redirect(url_for('posts.post_detail', slug=post.slug))
            
    return render_template('posts/post_create.html', form=form)
    
@posts.route('/<slug>/edit', methods=['POST', 'GET'])
@login_required
def post_update(slug):
    post = Post.query.filter(Post.slug==slug).first()
    
    if request.method == 'POST':
        form = PostForm(formdata=request.form, obj=post)
        form.populate_obj(post)
        db.session.commit()
        return redirect(url_for('posts.post_detail', slug=post.slug))
    
    form = PostForm(obj=post)
    return render_template('posts/edit.html', post=post, form=form)
    
    

views.py
from flask import render_template
from app import app


@app.route('/index')
@app.route('/')
def index():
    return render_template('index.html')
    


@app.errorhandler(404)
def page_not_found(e):
    return render_template('404.html'), 404

posts/templates/posts/edit.html
{% extends 'base.html' %}

{% block title %}	
	Update Post
{% endblock %}

{% block content %}	
	<h1>Edit {{ post.title }} Post </h1>
	<form action="{{ url_for('posts.post_update', slug=post.slug) }}" method="POST">
		{% for field in form %}
			<div class="form-group">
				{{ field.label() }}
				{{ field(class='form-control') }}
			</div>
		{% endfor %}
		<button class="btn btn-primay">Salvar</button>
		
	</form>
	
{% endblock %}

posts/templates/posts/post_create.html
{% extends 'base.html' %}

{% block title %}	
	Create new Post
{% endblock %}

{% block content %}	
	<h1>Create new Post </h1>
	<form action="{{ url_for('posts.post_create') }}" method="POST">
		{% for field in form %}
			<div class="form-group">
				{{ field.label() }}
				{{ field(class='form-control') }}
			</div>
		{% endfor %}
		<button class="btn btn-primay">Salvar</button>
		
	</form>
	
{% endblock %}

posts/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block title %}	
	{{ post.title }}
{% endblock %}

{% block content %}	
	<h1>{{ post.title }} </h1>
	<div class="">
		{{ post.body }}
	</div>
	
{% endblock %}

posts/templates/posts/posts.html
{% extends 'base.html' %}

{% block title %}	
	posts list
{% endblock %}

{% block content %}	
	<h1>Posts </h1>
	{% for post in posts %}	
		<div class="card mb-4">
		  <div class="card-header">
			{{ post.created.date() }}
		  </div>
		  <div class="card-body">
			<h5 class="card-title">
				<a href="{{ url_for('posts.post_detail', slug=post.slug) }}">
					{{ post.title }}
				</a>
			</h5>
			<p class="card-text">{{ post.body }}</p>
			<a href="{{ url_for('posts.post_detail', slug=post.slug) }}" class="btn btn-light">Go somewhere</a>
		  </div>
		  
		</div>
		{% if post.tags.count() %}
			<div class="card-footer text-muted">
				{% for tag in posts.tags %}
					<span class="badge badge-info">{{tag.title}}</span>
				{% endfor %}
			</div>
		{% endif %}
	{% endfor %}
	
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
    <head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<meta name="description" content="">
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
		<link rel="stylesheet" href="/static/css/styles.css">
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
		<title>
			{% block title %}
			{% endblock %}
			
		</title>

   </head>
	
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-5">
			<div class="container-fluid">
				<a class="navbar-brand" href="{{ url_for('index') }}">Flask</a>
				<a class="navbar-brand" href="{{ url_for('posts.posts_list') }}">Blog</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
				  <span class="navbar-toggler-icon"></span>
				</button>
				
				
				<div class="collapse navbar-collapse" id="navbarSupportedContent">
				  <ul class="navbar-nav me-auto mb-2 mb-lg-0">
					
					{% if current_user.has_role('admin') %}
						<li class="nav-item">
						  <a class="nav-link" href="{{ url_for('posts.post_create')}}">+ New Post</a>
						</li>
						
						<li class="nav-item">
						  <a class="nav-link" href="/admin"> Admin</a>
						</li>
						
						
					{% endif %}
					{% if current_user.is_authenticated %}
						<li class="nav-item">
						  <a class="nav-link" href="{{ url_for('security.logout') }}"> Logout</a>
						</li>
					{% else %}
						<li class="nav-item">
						  <a class="nav-link" href="{{ url_for('security.login') }}"> Login</a>
						</li>
					{% endif %}
				  </ul>
				  <form class="d-flex" role="search" method="GET">
					<input class="form-control me-2" type="search" placeholder="Search" name="q">
					<button class="btn btn-outline-success" type="submit">Search</button>
				  </form>
				</div>
			</div>
		</nav>
		
		<div class="container">
			<div class="row">
				<div class="col-8 mx-auto">
					{% block content %}
					{% endblock %}
				</div>
			</div>
		</div>
		
		


    </body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}	
	index page
{% endblock %}

{% block content %}	
	<h1>Home</h1>
{% endblock %}